# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Deploy APIs to Cloud Function
'on':
  workflow_dispatch:
    inputs:
      functions:
        description: "Enter functions to deploy (comma-separated, e.g., admin,ai)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract functions
        run: |
          IFS=',' read -ra FUNCTIONS <<< "${{ github.event.inputs.functions }}"
          for fn in "${FUNCTIONS[@]}"; do
            echo "Deploying function: $fn"
            # Add deployment command here
          done
